### PR TITLE
Bumping log4cats and natchez to latest version

### PR DESCRIPTION
**Pull request by SethLasky**
Hey all, I'd like to bump these versions in the next release if possible!

### CODE REVIEW

**Comment by Baccata** [comment]
Hey folks, is there a timeframe on including these bumps ? (in particular the bump of the natchez major version) ?

**Comment by massimosiani** [comment]
+1

**Comment by brbrown25** [comment]
@voidcontext do you think you could give this a review?

**Comment by voidcontext** [comment]
Hi Everyone, sorry because of the delays. Our current external PR process is much more convoluted than it should be. Once this is sorted (see #93) it should be quicker to accept contributions.

**Comment by voidcontext** [comment]
@SethLasky There are some compilation errors, maybe due to backwards incompatibility in `natchez`?

**Comment by brbrown25** [comment]
@voidcontext I have created https://github.com/ovotech/natchez-extras/pull/96 which should address the failing tests.

**Comment by voidcontext** [comment]
Closing this in favour of #101

**Pull request closed without merging**
